### ISSUE TITLE
Beancount Language Syntax doesn't appear in menu under User Documentation

### ISSUE THREAD

**Issue by alexjj** [aumayr/beancount-docs-static#3]
The menu on the left on this [page](https://aumayr.github.io/beancount-docs-static/users/index.html), doesn't show the Beancount Langauge Syntax link.
![image](https://cloud.githubusercontent.com/assets/440939/13795552/bf6dd65c-eabe-11e5-8fe8-ae47044cb593.png)

It only shows 13 out of the 14 pages listed on the right handside

**Comment by alexjj** [comment]
This could be because the URL is wrong.

The link from the User Documentation page links:
https://aumayr.github.io/beancount-docs-static/users/language.html

but the actual page is (found using the search):
https://aumayr.github.io/beancount-docs-static/users/languange.html

**Comment by aumayr** [comment]
Thanks for catching this glitch - fixed in https://bitbucket.org/aumayr/beancount/commits/7cbd01fe184c18d5c41b6056f6d40dace39555ef?at=default
